# PLACEHOLDERS FOR ARGUMENTS
#
# PLAYERS_LIST = list of all online players
# WORLDS_LIST = list of all worlds in the server
# MATERIAL_LIST = list of all materials
# ENCHANTMENTS_LIST = list of all enchantments
# POTION_EFFECTS_LIST = list of all potion effects
# ENTITY_TYPES_LIST = list of all entity types
#

commands:
  example:
    permission: "examplecommand.tabcomplete"
    arg-1:
      - "get"
      - "give"
    arg-2:
      - MATERIAL_LIST
    arg-3:
      - PLAYERS_LIST
    arg-4:
      - ENCHANTMENTS_LIST

  example_2:
    permission: "" # EMPTY = NO PERMISSION
    arg-1:
      - "selworld"
    arg-2:
      - WORLDS_LIST