# PLACEHOLDERS FOR ARGUMETS
#
# PLAYERS_LIST = list of all online players
# WORLDS_LIST = list of all worlds in the server
# MATERIAL_LIST = list of all materials

commands:
  example:
    permission: "examplecommand.tabcomplete"
    arg-1:
      - "get"
      - "give"
    arg-2:
      - MATERIAL_LIST
    arg-3:
      - PLAYERS_LIST

  example_2:
    permission: "" # EMPTY = NO PERMISSION
    arg-1:
      - "selworld"
    arg-2:
      - WORLDS_LIST