name: SkTabCompleter
version: 1.0.1

main: it.xoxryze.skTabCompleter.SkTabCompleter
api-version: '1.21.1'
depend:
  - Skript

authors: [ RyZeeTheBest ]
load: POSTWORLD

commands:
  sktabcompleter:
    permission: sktabcompleter.command